**1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.**

In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)

int64


**2. Given a NumPy array 'arr', check if its data type is float64.**

In [ ]:
arr = np.array([1.5, 2.6, 3.7])

if arr.dtype == np.float64:
    print("The data type of arr is float64.")
else:
    print("The data type of arr is not float64.")

The data type of arr is float64.


 **3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.**

In [ ]:
x = 3 + 4j
y = 5 + 6j
z = 7 + 8j
arr = np.array([x,y,z])
print(arr.dtype)

complex128


**4. Convert an existing NumPy array 'arr' of integers to float32 data type.**

In [ ]:
# integer array
a = np.array([1, 2, 3, 4, 5])
print(a.dtype)

# convert to float32
a = a.astype('float32')
print(a.dtype)
a


int64
float32


array([1., 2., 3., 4., 5.], dtype=float32)

**5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.**

In [ ]:
# float64 data type array
arr = np.array([1.1, 2.2, 3.3])
print(arr)
print(arr.dtype)

# convert to float32
arr = arr.astype('float32')
print(arr)
print(arr.dtype)

[1.1 2.2 3.3]
float64
[1.1 2.2 3.3]
float32


 **6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.**

In [ ]:
import numpy as np

def array_attributes():
  list_array = []

  n = int(input("Enter the number of elements in the array: "))
  for i in range(n):
    ele = int(input("Element : "))
    list_array.append(ele)

  print(list_array)
  # convert the list to a NumPy array
  arr = np.array(list_array)
  print(arr)

  '''
    This function takes a NumPy array as input and returns its shape, size, and data type.
  '''

  # get the shape, size, and data type of the array
  shape = arr.shape
  size = arr.size
  dtype = arr.dtype

  print("Shape:", shape)
  print("Size:", size)
  print("Data type:", dtype)

array_attributes()

Enter the number of elements in the array: 5
Element : 1
Element : 2
Element : 3
Element : 4
Element : 5
[1, 2, 3, 4, 5]
[1 2 3 4 5]
Shape: (5,)
Size: 5
Data type: int64


**7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.**

In [ ]:
def array_dimenesion():
  input_string = input('Enter elements of a list separated by space \n')
  user_list = input_string.split()
  print('string list: ', user_list)

# convert each item to int type
  for i in range(len(user_list)):
    # convert each item to int type
      user_list[i] = int(user_list[i])

  print(f'User list: , {np.array(user_list)}')
  print(f'Number of dimensions: {np.array(user_list).ndim}')
array_dimenesion()

Enter elements of a list separated by space 
1 2 3 4 5
string list:  ['1', '2', '3', '4', '5']
User list: , [1 2 3 4 5]
Number of dimensions: 1


**8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.**

In [ ]:
def item_size_info():
  input_string = input('Enter elements of a list separated by space \n')
  user_list = input_string.split()
  print('string list: ', user_list)
  # convert each item to int type
  for i in range(len(user_list)):
    # convert each item to int type
      user_list[i] = int(user_list[i])

      # convert the list to a NumPy array
  arr = np.array(user_list)
  print(arr)

  # get the item size and total size in bytes
  item_size = arr.itemsize
  total_size = arr.nbytes

  print("Item size:", item_size, "bytes")
  print("Total size:", total_size, "bytes")

item_size_info()


Enter elements of a list separated by space 
1 2 3 4 5
string list:  ['1', '2', '3', '4', '5']
[1 2 3 4 5]
Item size: 8 bytes
Total size: 40 bytes


**9.  Create a function array_strides that takes a NumPy array as input and returns the strides of the array.**

In [ ]:
def array_strides():
  input_string = input('Enter elements of a list separated by space \n')
  user_list = input_string.split()
  print('string list: ', user_list)
  # convert each item to int type
  for i in range(len(user_list)):
    # convert each item to int type
      user_list[i] = int(user_list[i])

      # convert the list to a NumPy array
  arr = np.array(user_list)
  print(arr)
  # get the strides of the array
  strides = arr.strides

  print("Strides:", strides)

array_strides()


Enter elements of a list separated by space 
1 2 3 4 5 6
string list:  ['1', '2', '3', '4', '5', '6']
[1 2 3 4 5 6]
Strides: (8,)


**10.  Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.**

In [ ]:
def shape_stride_relationship():

  input_string = input('Enter elements of a list separated by space \n')
  user_list = input_string.split()
  print('string list: ', user_list)
  # convert each item to int type
  for i in range(len(user_list)):
    # convert each item to int type
      user_list[i] = int(user_list[i])

      # convert the list to a NumPy array
  arr = np.array(user_list)
  print(arr)
  # get the shape and strides of the array
  shape = arr.shape
  strides = arr.strides

  print("Strides:", strides)
  print("Shape:", shape)

shape_stride_relationship()


Enter elements of a list separated by space 
1 2 3 4 5
string list:  ['1', '2', '3', '4', '5']
[1 2 3 4 5]
Strides: (8,)
Shape: (5,)


**11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements.**

In [ ]:
def create_zeros_array():
  n = int(input("Enter the number of elements in the array: "))
  arr = np.zeros(n)
  print(arr)

create_zeros_array()

Enter the number of elements in the array: 3
[0. 0. 0.]


**12.  Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`.**

In [ ]:
def create_ones_matrix():
  rows = int(input("Enter the number of rows: "))
  cols = int(input("Enter the number of columns: "))
  arr = np.ones((rows, cols))
  print(arr)

create_ones_matrix()

Enter the number of rows: 3
Enter the number of columns: 3
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


 **13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.**

In [ ]:
def generate_range_array():
  start = int(input("Enter the start of the range: "))
  stop = int(input("Enter the end of the range: "))
  step = int(input("Enter the step of the range: "))

  arr = np.arange(start, stop, step)
  print(arr)

generate_range_array()

Enter the start of the range: 1
Enter the end of the range: 10
Enter the step of the range: 2
[1 3 5 7 9]


**14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).**

In [ ]:
def generate_linear_space():
  start = float(input("Enter the start of the range: "))
  stop = float(input("Enter the end of the range: "))
  num = int(input("Enter the number of values: "))

  arr = np.linspace(start, stop, num)
  print(arr)

generate_linear_space()

Enter the start of the range: 1
Enter the end of the range: 10
Enter the number of values: 2
[ 1. 10.]


**15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.**

In [ ]:
def create_ones_matrix():
  n = int(input("Enter the number of rows: "))
  arr = np.eye(n)
  print(arr)

create_ones_matrix()


Enter the number of rows: 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**16. Write a function that takes a Python list and converts it into a NumPy array.**

In [ ]:
# Write a function that takes a Python list and converts it into a NumPy array.

def convert_list_to_array():
  input_string = input('Enter elements of a list separated by space \n')
  user_list = input_string.split()
  print('string list: ', user_list)
  # convert each item to int type
  for i in range(len(user_list)):
    # convert each item to int type
      user_list[i] = int(user_list[i])

      # convert the list to a NumPy array
  arr = np.array(user_list)
  print(arr)

convert_list_to_array()

Enter elements of a list separated by space 
1 2 3 4
string list:  ['1', '2', '3', '4']
[1 2 3 4]


**17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.**

In [ ]:
# create a 2D array

original_array = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Original array:  {original_array}")

# view the array
view_array = original_array.view()
print(f"View array:  {view_array}")

# change the value in the view array
view_array[0, 0] = 10

# print the original array
print(f"Original array:  {original_array}")




Original array:  [[1 2 3]
 [4 5 6]]
View array:  [[1 2 3]
 [4 5 6]]
Original array:  [[10  2  3]
 [ 4  5  6]]


**18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.**


In [ ]:
# define function

def concatenate_arrays(arr1, arr2, axis = 0):
  return np.concatenate((arr1, arr2), axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

concatenate_arrays(arr1, arr2, axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

**19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`**

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])


print(np.concatenate((arr1, arr2), axis=1))


[[1 2 5 6]
 [3 4 7 8]]


**20. Write a function that vertically stacks multiple NumPy arrays given as a list.**

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


**21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size.**

In [ ]:
def numpy_arange(start, stop, step):
  return np.arange(start, stop, step)


numpy_arange(1, 10, 2)

array([1, 3, 5, 7, 9])

**22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive)**

In [ ]:
def numpy_linspace(start, stop, num):
  return np.linspace(start, stop, num)

numpy_linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).**

In [ ]:
def numpy_logspace(start, stop, num):
  return np.logspace(start, stop, num)

numpy_logspace(1, 1000, 5)

/usr/local/lib/python3.10/dist-packages/numpy/core/function_base.py:298: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

**24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100**

In [ ]:
array = np.random.randint(1, 100, size=(5, 3))

print(array)

import pandas as pd

df = pd.DataFrame(array)
df

[[61 28 48]
 [39 86 98]
 [11 88 17]
 [72 72 37]
 [96 48 44]]


0   1   2
0  61  28  48
1  39  86  98
2  11  88  17
3  72  72  37
4  96  48  44

**25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.**

In [ ]:

def replace_negative_values_with_zeroes(df, column_name):
  df[column_name] = np.where(df[column_name] < 0, 0 , df[column_name])

  return df

df = pd.DataFrame({'A': [1, -2, 3, -4, 5], 'B': [6, -7, 8, -9, 10]})
df

replace_negative_values_with_zeroes(df, 'A')




A   B
0  1   6
1  0  -7
2  3   8
3  0  -9
4  5  10

**26. Access the 3rd element from the given NumPy array.**

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[2])

30


**27. Retrieve the element at index (1, 2) from the 2D NumPy array.**


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)
# retrieve index(1,2)

print(arr_2d[1, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


**28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.**

In [ ]:
arr = np.array([3, 8, 2, 10, 5, 7])

# boolean indexing
print(arr[arr > 5])


[ 8 10  7]


 **29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.**

In [ ]:
arrr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arrr[2:6]

array([3, 4, 5, 6])

 **30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.**

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)

# extract the sub-array

sub_array = arr_2d[0:2, 1:3]
print(sub_array)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


**31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.**

In [ ]:
def extract_elements(arr, indices):
  return arr[indices]

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([1, 0, 2])

print(extract_elements(arr, indices))


[[4 5 6]
 [1 2 3]
 [7 8 9]]


**32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.**

In [ ]:
def filter_elements(arr, threshold):
  return arr[arr > threshold]

arr = np.array([3, 8, 2, 10, 5, 7])
threshold = 5

print(filter_elements(arr, threshold))

[ 8 10  7]


 **33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.**

In [ ]:
def extract_elements(arr, indices1, indices2, indices3):
  return arr[indices1, indices2, indices3]


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

indices1 = np.array([0, 1])
indices2 = np.array([0, 1])
indices3 = np.array([0, 1])

extract_elements(arr, indices1, indices2, indices3)

array([ 1, 11])

**34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing.**

In [ ]:
def extract_elements(arr, condition1, condition2):
  return arr[condition1 & condition2]


arr = np.array([3, 8, 2, 10, 5, 7])
condition1 = arr > 5
condition2 = arr % 2 == 0

extract_elements(arr, condition1, condition2)

array([ 8, 10])

**35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.**

In [ ]:
def extract_elements(arr, row_indices, col_indices):
  return arr[row_indices, col_indices]

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr
row_indices = np.array([0, 1])
col_indices = np.array([1, 2])

extract_elements(arr, row_indices, col_indices)

array([2, 6])

**36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.**

In [ ]:
import numpy as np

# Numpy array and a scalar
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
scalar = 5

print("Array 1:", array1)
print("Scalar:", scalar)

# Using numpy.add() with an array and a scalar
result = np.add(array1, scalar)

print("Result of adding array and scalar:", result)

Array 1: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Scalar: 5
Result of adding array and scalar: [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


 **37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.**

In [ ]:
arr1 = np.array([[1], [2], [3]])
print(arr1)
arr2 = np.array([[4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
print(arr2)

arr1 * arr2




[[1]
 [2]
 [3]]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 4,  5,  6,  7],
       [16, 18, 20, 22],
       [36, 39, 42, 45]])

**38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.**

In [ ]:
arr1 = np.array([[1], [2], [3], [4]])
print(arr1)
arr2 = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(arr2)


arr1 + arr2

[[1]
 [2]
 [3]
 [4]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

**39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.**

In [ ]:
arr1 = np.array([[1], [2], [3]])
print(arr1)
arr2 = np.array([[4, 5, 6]])
print(arr2)

arr1 + arr2

[[1]
 [2]
 [3]]
[[4 5 6]]


array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

**40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.**

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)
print(arr1.shape)
arr2 = np.array([[4, 5], [6, 7]])
print(arr2)
print(arr2.shape)








[[1 2 3]
 [4 5 6]]
(2, 3)
[[4 5]
 [6 7]]
(2, 2)


**41. Calculate column-wise mean for the given array:**

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

mean = np.mean(arr, axis=0)
print(mean)

[[1 2 3]
 [4 5 6]]
[2.5 3.5 4.5]


**42. Find maximum value in each row of the given array:**

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

max_value = np.max(arr, axis=1)
print(max_value)

[[1 2 3]
 [4 5 6]]
[3 6]


**43. For the given array, find indices of maximum value in each column**

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

max_indices = np.argmax(arr, axis=0)
print(max_indices)

[[1 2 3]
 [4 5 6]]
[1 1 1]


**44. For the given array, apply custom function to calculate moving sum along rows.**

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

def moving_sum(arr):
  return np.cumsum(arr, axis=1)

moving_sum(arr)

[[1 2 3]
 [4 5 6]]


array([[ 1,  3,  6],
       [ 4,  9, 15]])

**45. In the given array, check if all elements in each column are even.**

In [ ]:
arr = np.array([[2, 4, 6], [3, 5, 7]])

print(arr)

all_even = np.all(arr % 2 == 0, axis=0)
print(all_even)


[[2 4 6]
 [3 5 7]]
[False False False]


**46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.**

In [ ]:
original_array = np.array([1, 2, 3, 4, 5, 6])
m = 2
n = 3

reshaped_matrix = original_array.reshape(m, n)
print(reshaped_matrix)




[[1 2 3]
 [4 5 6]]


47. Create a function that takes a matrix as input and returns the flattened array.

In [ ]:
def flatten_matrix(matrix):
  return matrix.flatten()


input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flatten_matrix(input_matrix)

array([1, 2, 3, 4, 5, 6])

**48. Write a function that concatenates two given arrays along a specified axis.**

In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

def concatenate_arrays(array1, array2, axis=0):
  return np.concatenate((array1, array2), axis=axis)

concatenate_arrays(array1, array2, axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

**49. Create a function that splits an array into multiple sub-arrays along a specified axis.**

In [ ]:
import numpy as np
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def split_array(array, n, axis):
  return np.array_split(array, n, axis = 1)

split_array(original_array, 3, axis = 1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

**50. Write a function that inserts and then deletes elements from a given array at specified indices.**

In [ ]:
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

def insert_and_delete(array, indices_to_insert, values_to_insert, indices_to_delete):


  array = np.insert(array, indices_to_insert, values_to_insert)
  array = np.delete(array, indices_to_delete)

  return array
  print(array)

insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)



array([ 1, 10,  4, 11,  5])

**51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.**

In [ ]:
from numpy import random
arr1 = random.randint(100, size=(5))
arr2 = random.randint(10, size=(5))

print(arr1)
print(arr2)

arr1 + arr2

[45 30  4  9 25]
[4 1 9 0 4]


array([49, 31, 13,  9, 29])

**52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise.**

In [ ]:
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)

print(arr1)
print(arr2)

arr1 - arr2


[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10]


array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

**53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.**

In [ ]:
arr1 = random.randint(100, size=(5))
arr2 = random.randint(5, size=(5))

print(f"arr1 = {arr1}")
print(f"arr2 = {arr2}")

arr1 * arr2


arr1 = [74 93 75 12 49]
arr2 = [0 3 1 4 4]


array([  0, 279,  75,  48, 196])

**54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.**

In [ ]:
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)

print(f"arr1 = {arr1}")
print(f"arr2 = {arr2}")

arr1 / arr2

arr1 = [ 2  4  6  8 10]
arr2 = [1 2 3 4 5]


array([2., 2., 2., 2., 2.])

**55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.**

In [ ]:
arr1 = np.arange(1, 6)
arr2 = np.arange(5, 0, -1)

print(f"arr1 = {arr1}")
print(f"arr2 = {arr2}")

arr1 ** arr2

arr1 = [1 2 3 4 5]
arr2 = [5 4 3 2 1]


array([ 1, 16, 27, 16,  5])

**56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.**

In [ ]:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

def count_substring(arr, substring):
  count = 0
  for string in arr:
    if substring in string:
      count += 1
  return count

count_substring(arr, 'hello')

3

**57. Write a function that extracts uppercase characters from a NumPy array of strings.**

In [ ]:
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

def extract_uppercase_characters(arr):
  uppercase_characters = []
  for string in arr:
    for char in string:
      if char.isupper():
        uppercase_characters.append(char)
  return uppercase_characters

extract_uppercase_characters(arr)

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']

**58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.**

In [ ]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def replace_substring(arr, old_substring, new_substring):
  new_arr = []
  for string in arr:
    new_arr.append(string.replace(old_substring, new_substring))
  return new_arr

replace_substring(arr, 'apple', 'orange')


['orange', 'banana', 'grape', 'pineorange']

**59. Write a function that concatenates strings in a NumPy array element-wise.**

In [ ]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

def concatenate_strings(arr1, arr2):
  return np.char.add(arr1, arr2)

concatenate_strings(arr1, arr2)


array(['HelloOpen', 'WorldAI'], dtype='<U9')

**60. Write a function that finds the length of the longest string in a NumPy array.**

In [ ]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def find_longest_string(arr):
  max_length = 0
  for string in arr:
    if len(string) > max_length:
      max_length = len(string)
  return max_length

find_longest_string(arr)


9

**61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.**

In [ ]:
df = np.random.randint(1, 1000, 100)
df
print(f'Mean = {df.mean()})')
print(f'Median = {np.median(df)}')
print(f'Variance = {df.var()}')
print(f'Standard Deviation = {df.std()}')




Mean = 474.69)
Median = 483.0
Variance = 83857.2739
Standard Deviation = 289.58120432790525


**62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.**

In [ ]:
array = np.random.randint(1, 100, 50)
print(array)

# Find the 25th and 75th percentiles
print(f'25th percentile = {np.percentile(array, 25)}')
print(f'75th percentile = {np.percentile(array, 75)}')


[89 85 92 36 84 22 74 44 62 24 44 53 82 16 22 78 24 25 73 73 32 56 99 96
 39 38 32 65 98 86 11 28 50 17 35 44 44 39 98 72 89 54 33 67 10 56 55 14
 24 19]
25th percentile = 29.0
75th percentile = 73.75


**63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.**

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

np.corrcoef(arr1, arr2)


array([[1., 1.],
       [1., 1.]])

**64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.**

In [ ]:
# input two matrices
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])

# This will return dot product
res = np.dot(mat1,mat2)


# print resulted matrix
print(res)

[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


**65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.**

In [ ]:
arr = np.random.randint(10, 1000, 50)
print(arr)
print(f"10th percentile = {np.percentile(arr, 10)}")
print(f"50th percentile = {np.percentile(arr, 50)}")
print(f"90th percentile = {np.percentile(arr, 90)}")



[781 130 804 557 846 178 683 193 742 136 563 917 260 348 650 418 126  43
  25 407 850 325 663 302  46 363 607 102 987 730 168 631 825 726 571  19
 589 618 519  92 646 157 798 296  43 852 946 903 304 567]
10th percentile = 87.40000000000002
50th percentile = 560.0
90th percentile = 850.2


**66. Create a NumPy array of integers and find the index of a specific element.**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr)
print(np.where(arr == 5))


[ 1  2  3  4  5  6  7  8  9 10]
(array([4]),)


**67. Generate a random NumPy array and sort it in ascending order.**

In [ ]:
arr = np.random.randint(1, 100, 10)
print(f"Random array : {arr}")
print(f"Sort it in ascending order = {np.sort(arr)}")


Random array : [73 69 47 76 81 84 84  6  5 51]
Sort it in ascending order = [ 5  6 47 51 69 73 76 81 84 84]


**68. Filter elements >20  in the given NumPy array.**

In [ ]:
arr = np.array([12, 25, 6, 42, 8, 30])
print(f"array : {arr}")
print(f"Filtering array elements > 20 : {arr[arr > 20]}")

array : [12 25  6 42  8 30]
Filtering array elements > 20 : [25 42 30]


**69. Filter elements which are divisible by 3 from a given NumPy array.**

In [ ]:
arr = np.array([1, 5, 8, 12, 15])

print(f"array : {arr}")
print(f"Filtering array elements which are divisible by 3 : {arr[arr % 3 == 0]}")

array : [ 1  5  8 12 15]
Filtering array elements which are divisible by 3 : [12 15]


**70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.**

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(f"array : {arr}")
print(f"Filtering array elements which are >= 20 and <= 40 : {arr[(arr >= 20) & (arr <= 40)]}")

array : [10 20 30 40 50]
Filtering array elements which are >= 20 and <= 40 : [20 30 40]


**71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.**

In [ ]:
arr = np.array([1, 2, 3])

print(f"array : {arr}")
print(f"Byte order of array :-  {arr.dtype.byteorder}")

array : [1 2 3]
Byte order of array :-  =


**72. For the given NumPy array, perform byte swapping in place using `byteswap()`.**

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)

print(f"array : {arr}")
print(f"Byte swapping of array :-  {arr.byteswap()}")

array : [1 2 3]
Byte swapping of array :-  [16777216 33554432 50331648]


**73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.**

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)

print(f"array : {arr}")
arr_swap = arr.byteswap()

print(f"Byte swapping of array :-  {arr_swap.dtype.newbyteorder()}")


array : [1 2 3]
Byte swapping of array :-  >i4


**74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.**

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)


print(f"array : {arr}")
arr_swap = arr.byteswap()

print(f"Byte swapping of array :-  {arr_swap.dtype.newbyteorder()}")


array : [1 2 3]
Byte swapping of array :-  >i4


**75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`.**

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)
import sys

# check if byte swapping is necessary
arr.dtype.byteorder
endianness_map = {
    '>': 'big',
    '<': 'little',
    '=': sys.byteorder,
    '|': 'not applicable',
}
print(endianness_map)

{'>': 'big', '<': 'little', '=': 'little', '|': 'not applicable'}


**76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.**

In [2]:
import numpy as np
arr1 = np.arange(1, 11)
print(f"arr1 = {arr1}")
copy_arr = arr1.copy()
copy_arr[0] = 100
print(f"copy_arr = {copy_arr}")
print(f"arr1 = {arr1}")



arr1 = [ 1  2  3  4  5  6  7  8  9 10]
copy_arr = [100   2   3   4   5   6   7   8   9  10]
arr1 = [ 1  2  3  4  5  6  7  8  9 10]


**77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.**

In [3]:
matrix = np.random.randint(1, 10, (3, 3))
print(f"matrix = {matrix}")
view_slice = matrix[1:, 1:]
print(f"view_slice = {view_slice}")
view_slice[0, 0] = 100
print(f"matrix = {matrix}")


matrix = [[4 6 7]
 [7 5 9]
 [6 2 6]]
view_slice = [[5 9]
 [2 6]]
matrix = [[  4   6   7]
 [  7 100   9]
 [  6   2   6]]


**78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.**

In [4]:
array_a = np.arange(1, 13).reshape(4, 3)
print(f"array_a = {array_a}")
view_b = array_a[1:3, 1:]
print(f"view_b = {view_b}")
view_b += 5
print(f"array_a = {array_a}")


array_a = [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
view_b = [[5 6]
 [8 9]]
array_a = [[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]


**79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.**

In [5]:
orig_array = np.arange(1, 9).reshape(2, 4)
print(f"orig_array = {orig_array}")
reshaped_view = orig_array.reshape(4, 2)
print(f"reshaped_view = {reshaped_view}")
reshaped_view[0, 0] = 100
print(f"orig_array = {orig_array}")



orig_array = [[1 2 3 4]
 [5 6 7 8]]
reshaped_view = [[1 2]
 [3 4]
 [5 6]
 [7 8]]
orig_array = [[100   2   3   4]
 [  5   6   7   8]]


**80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data.**

In [6]:
data = np.random.randint(1, 10, (3, 4))
print(f"data = {data}")
data_copy = data[data > 5].copy()
print(f"data_copy = {data_copy}")

data_copy[0] = 100
print(f"data = {data}")
print(f"data_copy = {data_copy}")


data = [[5 4 3 9]
 [7 8 3 1]
 [1 8 5 6]]
data_copy = [9 7 8 8 6]
data = [[5 4 3 9]
 [7 8 3 1]
 [1 8 5 6]]
data_copy = [100   7   8   8   6]


**81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.**

In [7]:
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))
print(f"A = {A}")
print(f"B = {B}")

print(f"A + B = {A + B}")
print(f"A - B = {A - B}")


A = [[4 2 8]
 [2 5 3]
 [4 7 9]]
B = [[7 4 4]
 [7 7 9]
 [4 4 7]]
A + B = [[11  6 12]
 [ 9 12 12]
 [ 8 11 16]]
A - B = [[-3 -2  4]
 [-5 -2 -6]
 [ 0  3  2]]


**82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.**

In [8]:
C = np.random.randint(1, 10, (3, 2))
D = np.random.randint(1, 10, (2, 4))
print(f"C = {C}")
print(f"D = {D}")

print(f"C * D = {np.dot(C, D)}")



C = [[2 6]
 [2 6]
 [3 6]]
D = [[8 6 2 2]
 [6 8 2 2]]
C * D = [[52 60 16 16]
 [52 60 16 16]
 [60 66 18 18]]


**83. Create a matrix `E` and find its transpose.**

In [9]:
E = np.random.randint(1, 10, (3, 3))
print(f"E = {E}")
print(f"Transpose of E = {E.T}")


E = [[5 1 2]
 [1 6 6]
 [6 2 9]]
Transpose of E = [[5 1 6]
 [1 6 2]
 [2 6 9]]


**84. Generate a square matrix `F` and compute its determinant.**

In [10]:
F = np.random.randint(1, 10, (3, 3))
print(f"F = {F}")
print(f"Determinant of F = {np.linalg.det(F)}")



F = [[2 8 2]
 [5 7 4]
 [1 6 9]]
Determinant of F = -203.99999999999994


**85. Create a square matrix `G` and find its inverse.**

In [11]:
G = np.random.randint(1, 10, (3, 3))
print(f"G = {G}")
print(f"Inverse of G = {np.linalg.inv(G)}")



G = [[8 1 2]
 [2 6 1]
 [5 1 1]]
Inverse of G = [[-0.38461538 -0.07692308  0.84615385]
 [-0.23076923  0.15384615  0.30769231]
 [ 2.15384615  0.23076923 -3.53846154]]
